const actionTypes = {
  SEARCH_VIDEOS: 'SEARCH_VIDEOS',
  SEARCH_VIDEOS_SUCCESS: 'SEARCH_VIDEOS_SUCCESS',
  SEARCH_VIDEOS_ERROR: 'SEARCH_VIDEOS_ERROR',
  VIDEO_SELECT: 'VIDEO_SELECT',
  SET_THEME: 'SET_THEME',
  SET_FILTER: 'SET_FILTER',
};

export default actionTypes;
