const actionTypes = {
  SEARCH_VIDEOS: 'SEARCH_VIDEOS',
  SEARCH_VIDEOS_SUCCESS: 'SEARCH_VIDEOS_SUCCESS',
  SEARCH_VIDEOS_ERROR: 'SEARCH_VIDEOS_ERROR',
  VIDEO_SELECT: 'VIDEO_SELECT',
};

export default actionTypes;
